In [ ]:
# E-Commerce Order Analytics

## Advanced EDA and Feature Engineering

### Project 1 — DecodeLabs Data Science Training

This project focuses on transforming raw e-commerce order data into a clean, analysis-ready and machine-learning-ready dataset through:

- Exploratory Data Analysis
- Missing Value Treatment
- Outlier Detection
- Statistical Data Cleaning
- Feature Engineering

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
from sklearn.impute import KNNImputer

import warnings

warnings.filterwarnings("ignore")

sns.set_theme(style="whitegrid")

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
df = pd.read_excel(
    "../data/raw/Dataset for Data Analytics.xlsx"
)

df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [4]:
df.shape

(1200, 14)

In [ ]:
### Dataset Dimensions

The dataset contains 1,200 records and 14 columns. Each row represents an e-commerce order.

In [5]:
df.columns.tolist()

['OrderID',
 'Date',
 'CustomerID',
 'Product',
 'Quantity',
 'UnitPrice',
 'ShippingAddress',
 'PaymentMethod',
 'OrderStatus',
 'TrackingNumber',
 'ItemsInCart',
 'CouponCode',
 'ReferralSource',
 'TotalPrice']

In [6]:
df.head()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [7]:
df.tail()

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [8]:
df.sample(5)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1109,ORD201109,2024-04-08,C62277,Printer,4,77.47,474 Main St,Gift Card,Returned,TRK32026174,7,SAVE10,Instagram,309.88
260,ORD200260,2023-05-17,C12245,Monitor,2,407.79,153 Main St,Debit Card,Shipped,TRK22000463,3,NaN,Google,815.58
1107,ORD201107,2025-06-30,C25110,Tablet,2,63.21,282 Main St,Online,Cancelled,TRK80963328,4,SAVE10,Google,126.42
231,ORD200231,2023-11-05,C30955,Phone,4,41.90,327 Main St,Gift Card,Pending,TRK46898848,9,FREESHIP,Instagram,167.60

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: datetime64[us](1), float64(2), int64(2), str(9)
memory usage: 131.4 KB

In [10]:
df.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

In [11]:
df.describe(include="object")

,OrderID,CustomerID,Product,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,CouponCode,ReferralSource
count,1200,1200,1200,1200,1200,1200,1200,891,1200
unique,1200,1189,7,655,5,5,1200,3,5
top,ORD200000,C98474,Printer,533 Main St,Online,Cancelled,TRK37947903,FREESHIP,Instagram
freq,1,2,181,8,258,250,1,313,259

In [12]:
missing_summary = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Missing Percentage": (
        df.isnull().sum() / len(df) * 100
    )
})

missing_summary.sort_values(
    by="Missing Values",
    ascending=False
)

                 Missing Values  Missing Percentage
CouponCode                  309               25.75
OrderID                       0                0.00
CustomerID                    0                0.00
Product                       0                0.00
Quantity                      0                0.00
Date                          0                0.00
UnitPrice                     0                0.00
ShippingAddress               0                0.00
OrderStatus                   0                0.00
PaymentMethod                 0                0.00
TrackingNumber                0                0.00
ItemsInCart                   0                0.00
ReferralSource                0                0.00
TotalPrice                    0                0.00

In [13]:
duplicate_count = df.duplicated().sum()

print(
    f"Number of duplicate rows: {duplicate_count}"
)

Number of duplicate rows: 0

In [14]:
duplicate_order_ids = df["OrderID"].duplicated().sum()

print(
    f"Duplicate OrderIDs: {duplicate_order_ids}"
)

Duplicate OrderIDs: 0

In [15]:
for column in df.select_dtypes(
    include="object"
).columns:

    print(f"\n{column}")
    print(df[column].nunique())
    print(df[column].unique()[:10])

OrderID
1200
<StringArray>
['ORD200000', 'ORD200001', 'ORD200002', 'ORD200003', 'ORD200004', 'ORD200005',
 'ORD200006', 'ORD200007', 'ORD200008', 'ORD200009']
Length: 10, dtype: str

CustomerID
1189
<StringArray>
['C72649', 'C75739', 'C81728', 'C33540', 'C81840', 'C37249', 'C83492',
 'C41460', 'C26817', 'C31946']
Length: 10, dtype: str

Product
7
<StringArray>
['Monitor', 'Phone', 'Tablet', 'Chair', 'Printer', 'Laptop', 'Desk']
Length: 7, dtype: str

ShippingAddress
655
<StringArray>
['928 Main St', '823 Main St', '512 Main St', '275 Main St', '668 Main St',
 '934 Main St', '986 Main St', '706 Main St', '904 Main St', '102 Main St']
Length: 10, dtype: str

PaymentMethod
5
<StringArray>
['Debit Card', 'Online', 'Credit Card', 'Gift Card', 'Cash']
Length: 5, dtype: str

OrderStatus
5
<StringArray>
['Shipped', 'Cancelled', 'Returned', 'Delivered', 'Pending']
Length: 5, dtype: str

TrackingNumber
1200
<StringArray>
['TRK37947903', 'TRK91186779', 'TRK42903982', 'TRK62788070', 'TRK29241424',
 'TRK72976927', 'TRK96417362', 'TRK78809193', 'TRK61042692', 'TRK33478363']
Length: 10, dtype: str

CouponCode
3
<StringArray>
['SAVE10', 'FREESHIP', nan, 'WINTER15']
Length: 4, dtype: str

ReferralSource
5
<StringArray>
['Instagram', 'Referral', 'Email', 'Facebook', 'Google']
Length: 5, dtype: str